notifications:
  email: false

language: python

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = master)

jobs:
  include:
    - name: "Linux (quick)"
      python: 3.6
      env: arg=--quick

    - name: "Mac (quick)"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: arg=--quick
    
    - name: "Linux (full)"
      python: 3.6
      env: arg=""

    - name: "Mac (full)"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: arg=""
    
    - name: "Linux (params)"
      python: 3.6
      env: arg=--params

    - name: "Mac (params)"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: arg=--params

stages:
  - name: services
    if: os ==  linux

addons:
  apt:
    packages:
      - cmake
      - webkit2gtk-4.0
      - libboost-all-dev

services:
  - xvfb

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  # install Faust
  - cd modules/faust
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]];
    then bash run_tests.sh $arg;
    else sh run_tests.sh $arg;
    fi

cache:
  directories:
    - $HOME/.cache/pip
    - modules/faust
